--[[
    GD50
    Breakout Remake

    -- Powerup Class --

    Author: Brandon Pineda

    Represents a powerup that is randomly generated by a brick
]]

PowerUp = Class{}

-- Initialize powerup with broken brick coords
-- sking can be 0 for multiple balls or 1 for a key fr a locked brick
function PowerUp:init(startX, startY, skin)
    self.x = startX
    self.y = startY

    -- valocity when going down the screen
    self.dy = 15

    self.skin = skin

    self.isPickedUp = false

    self.enabled = false
end

function PowerUp:update(dt)
    -- Calculate new Y
    if (self.enabled) then
        self.y = math.max(0, self.y + self.dy * dt)
    end
end

-- Renders powerup only when enabled
function PowerUp:render()
    if (self.enabled and not self.isPickedUp) then
        love.graphics.draw(gTextures['main'], gFrames['powerUps'][self.skin],
            self.x, self.y)
    end
end

-- Look for pickup by paddle
function PowerUp:collides(paddle)
    -- first, check to see if the left edge of either is farther to the right
    -- than the right edge of the other
    if self.x > paddle.x - 8 and self.x + 16 < paddle.x + paddle.width + 8 and
        self.y > paddle.y - 8 and self.y < paddle.y + paddle.height + 8 then
        self.enabled = false

        -- Powerup picked up sound
        if self.skin == 1 then
            gSounds['powerupPickedUp']:play()
        else
            gSounds['keyPickedUp']:play()
        end

        return true
    else
        return false
    end
end